name: translate-qr-app
region: nyc
services:
- name: web
  github:
    branch: main
    deploy_on_push: true
    repo: zaeem-maqsood/translate-with-qrcodes
  dockerfile_path: Dockerfile
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    type: secret
  - key: ALLOWED_HOSTS
    value: "${APP_DOMAIN}"
  - key: APP_DOMAIN
    value: "${APP_DOMAIN}"
  - key: APP_SCHEME
    value: "https"
  - key: CSRF_TRUSTED_ORIGINS
    value: "${APP_URL}"
  - key: GOOGLE_CREDENTIALS_JSON
    type: secret
databases:
- engine: PG
  name: db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
